global:
    env: "DEV"
    loglevel: "INFO"
    nwsid: "UTC053"
    webdriver: "/usr/bin/chromedriver"
    smtp:
        host: ""
        port: 
        user: ""
        pass: ""
        from: ""
        to: ""
database:
    schema: ""
    user: ""
    password: ""
    host: ""
    host_ro: ""
spillman-api:
    url: ""
    token: ""
spillman:
    url: ""
    touch_url: ""
    user: ""
    password: ""
    sendrlog: "Y"
active911:
    sendalerts: "Y"
    update_delay: 60
    snpp:
        host: "snpp.active911.com"
        port: 444
        timeout: 5