version: '3'
services:
  spillman-automation:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/spillman-automation:prod
    container_name: spillman-automation
    environment:
      - TZ=America/Denver
    volumes:
      - "/etc/sccity/spillman-automation.env:/app/.env:ro"
    restart: unless-stopped
    user: "1435:1435"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M