version: '3'
services:
  spillman-automation:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/spillman-automation:prod
    container_name: spillman-automation
    environment:
      - TZ=America/Denver
    volumes:
      - "$PWD/config:/app/config"
    restart: unless-stopped
    user: "1435:1435"